apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartedu-deployment
  labels:
    app: smartedu-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartedu-app
  template:
    metadata:
      labels:
        app: smartedu-app
    spec:
      containers:
      - name: smartedu
        image: devopseasylearning/smartedu:latest   # Use your local image name and tag here
        #imagePullPolicy:     # Ensure it won't try to pull from a registry
        ports:
        - containerPort: 80 

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    app: smartedu-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 30249


