apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartedu-deployment
  labels:
    app: smartedu-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartedu-app
  template:
    metadata:
      labels:
        app: smartedu-app
    spec:
      containers:
      - name: smartedu
        image: devopseasylearning/smartedu:latest   # Use your local image name and tag here
        ports:
        - containerPort: 80
        # env: 
        # - name: USERNAME
        #   valueFrom:
        #     secretKeyRef: 
        #       name: smartedu-secret
        #       key: username
        # - name: PASSWORD
        #   valueFrom:
        #     secretKeyRef: 
        #       name: smartedu-secret
        #       key: password  
        # - name: DOCKERHUB_URL
        #   valueFrom:
        #     configMapKeyRef: 
        #       name: smartedu-config
        #       key: dockerhub_url
      imagePullSecrets:
      - name: smartedu-secret  # Reference to the secret if needed
